name: "CI: Linux Build (Default)"

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        sudo apt update
        sudo apt install libsdl2-dev
        cd src
        make
